name: build

on:
  push:
    branches: [master]

jobs:
  build_macos:
    name: Build for MacOS
    runs-on: macos-10.15
    steps:
    - {name: "Checkout", uses: actions/checkout@v2}
    - {name: "Checkout gofeed", uses: actions/checkout@v2, with: {repository: nkanaev/gofeed, path: gofeed}}
    - name: "Build"
      run: |
        make build_macos
        cd _output/macos && zip -r yarr-macos.zip yarr.app
    - {name: "Upload", uses: actions/upload-artifact@v2, with: {name: macos, path: _output/macos/yarr-macos.zip}}
